In [1]:
#import libraries
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
##creating fake dataset
fakedata=np.tile(np.array([1,2,3,4]),(10,1))+np.tile(10*np.arange(1,11),(4,1)).T
fakelabels=np.arange(10)>4
print(fakedata),print(' ')
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]
 
[False False False False False  True  True  True  True  True]


In [6]:
#tain test split
#we specify the sizes of partitions
#order is train,devset and test
partitions=[.8,.1,.1]


train_data,testTMP_data,train_labels,testTMP_labels=\
                                       train_test_split(fakedata,fakelabels,train_size=partitions[0])
# now we split the TMP data
split=partitions[1]/np.sum(partitions[1:])
devset_data,test_data,devset_labels,test_labels=\
                             train_test_split(testTMP_data,testTMP_labels,train_size=split)
  

#print out the size
# print out the sizes
print('Training data size: ' + str(train_data.shape))
print('Devset data size: '   + str(devset_data.shape))
print('Test data size: '     + str(test_data.shape))
print(' ')

# print out the train/test data
print('Training data: ')
print(train_data)
print(' ')

print('Devset data: ')
print(devset_data)
print(' ')

print('Test data: ')
print(test_data)

Training data size: (8, 4)
Devset data size: (1, 4)
Test data size: (1, 4)
 
Training data: 
[[101 102 103 104]
 [ 51  52  53  54]
 [ 81  82  83  84]
 [ 11  12  13  14]
 [ 31  32  33  34]
 [ 91  92  93  94]
 [ 61  62  63  64]
 [ 41  42  43  44]]
 
Devset data: 
[[71 72 73 74]]
 
Test data: 
[[21 22 23 24]]
